@startuml

autonumber

participant client #lime
participant server #lightblue
participant master #orange


client -> server: N_AUTHTRY

server -> master: reqauth

master -> master: checks\nuser db

server <-[#red]- master: failauth (if no user found)
note left: server sends an\n"identification failed"\nmessage to the client
server <[#green]- master: chalauth (if user found)

client <[#green]- server: N_AUTHCHAL

client -> client: calculate\nanswer\nchallenge

client -> server: N_AUTHANS

server -> master: confauth %u %s

master -> master: checkchallenge

master -[#red]-> server: failauth (if check fails)
note left: server sends an\n"identification failed"\nmessage to the client
server <[#green]- master: succauth %s %s %s

server -[#green]> client: setprivilege()
note over client: all clients are informed\nthat the user was identified\nand was assigned a role

@enduml
