name: CI

on: [push, pull_request]

jobs:
  content_checks:
    name: Content checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install pipx && pipx install poetry && poetry install
      - name: Link check
        run: poetry run make linkcheck
